FROM python:3.12-slim-bullseye

RUN apt update && apt install -y protobuf-compiler libprotobuf-dev --no-install-recommends

WORKDIR /character-creator

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install "fastapi[standard]"

COPY ./proto .
RUN protoc  --python_out=. character_messages.proto character_service.proto
COPY ./server/character-creator/ .

EXPOSE 8000
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0"]